package com.web.entity;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer empid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.profId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer profid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empSex
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empBirthDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date empbirthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empAge
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer empage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empSubsidiesSalary
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float empsubsidiessalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empMaritalStatus
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empmaritalstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empBirthPlace
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empbirthplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empNation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empnation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empIDnumber
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empidnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empNationality
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empnationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empWorkUnitAndAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String empworkunitandadr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String emptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empPostalCode
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String emppostalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empHkAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String emphkadr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empLinkmanName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String emplinkmanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empLinkmanAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String emplinkmanadr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empLinkmanRelation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String emplinkmanrelation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.empLinkmanTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String emplinkmantel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empId
     *
     * @return the value of employee.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empId
     *
     * @param empid the value for employee.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.profId
     *
     * @return the value of employee.profId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getProfid() {
        return profid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.profId
     *
     * @param profid the value for employee.profId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setProfid(Integer profid) {
        this.profid = profid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empName
     *
     * @return the value of employee.empName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empName
     *
     * @param empname the value for employee.empName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpname(String empname) {
        this.empname = empname == null ? null : empname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empSex
     *
     * @return the value of employee.empSex
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpsex() {
        return empsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empSex
     *
     * @param empsex the value for employee.empSex
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpsex(String empsex) {
        this.empsex = empsex == null ? null : empsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empBirthDate
     *
     * @return the value of employee.empBirthDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getEmpbirthdate() {
        return empbirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empBirthDate
     *
     * @param empbirthdate the value for employee.empBirthDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpbirthdate(Date empbirthdate) {
        this.empbirthdate = empbirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empAge
     *
     * @return the value of employee.empAge
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getEmpage() {
        return empage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empAge
     *
     * @param empage the value for employee.empAge
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpage(Integer empage) {
        this.empage = empage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empSubsidiesSalary
     *
     * @return the value of employee.empSubsidiesSalary
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getEmpsubsidiessalary() {
        return empsubsidiessalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empSubsidiesSalary
     *
     * @param empsubsidiessalary the value for employee.empSubsidiesSalary
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpsubsidiessalary(Float empsubsidiessalary) {
        this.empsubsidiessalary = empsubsidiessalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empMaritalStatus
     *
     * @return the value of employee.empMaritalStatus
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpmaritalstatus() {
        return empmaritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empMaritalStatus
     *
     * @param empmaritalstatus the value for employee.empMaritalStatus
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpmaritalstatus(String empmaritalstatus) {
        this.empmaritalstatus = empmaritalstatus == null ? null : empmaritalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empBirthPlace
     *
     * @return the value of employee.empBirthPlace
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpbirthplace() {
        return empbirthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empBirthPlace
     *
     * @param empbirthplace the value for employee.empBirthPlace
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpbirthplace(String empbirthplace) {
        this.empbirthplace = empbirthplace == null ? null : empbirthplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empNation
     *
     * @return the value of employee.empNation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpnation() {
        return empnation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empNation
     *
     * @param empnation the value for employee.empNation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpnation(String empnation) {
        this.empnation = empnation == null ? null : empnation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empIDnumber
     *
     * @return the value of employee.empIDnumber
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpidnumber() {
        return empidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empIDnumber
     *
     * @param empidnumber the value for employee.empIDnumber
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpidnumber(String empidnumber) {
        this.empidnumber = empidnumber == null ? null : empidnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empNationality
     *
     * @return the value of employee.empNationality
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpnationality() {
        return empnationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empNationality
     *
     * @param empnationality the value for employee.empNationality
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpnationality(String empnationality) {
        this.empnationality = empnationality == null ? null : empnationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empWorkUnitAndAdr
     *
     * @return the value of employee.empWorkUnitAndAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmpworkunitandadr() {
        return empworkunitandadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empWorkUnitAndAdr
     *
     * @param empworkunitandadr the value for employee.empWorkUnitAndAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpworkunitandadr(String empworkunitandadr) {
        this.empworkunitandadr = empworkunitandadr == null ? null : empworkunitandadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empTel
     *
     * @return the value of employee.empTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmptel() {
        return emptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empTel
     *
     * @param emptel the value for employee.empTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmptel(String emptel) {
        this.emptel = emptel == null ? null : emptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empPostalCode
     *
     * @return the value of employee.empPostalCode
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmppostalcode() {
        return emppostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empPostalCode
     *
     * @param emppostalcode the value for employee.empPostalCode
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmppostalcode(String emppostalcode) {
        this.emppostalcode = emppostalcode == null ? null : emppostalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empHkAdr
     *
     * @return the value of employee.empHkAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmphkadr() {
        return emphkadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empHkAdr
     *
     * @param emphkadr the value for employee.empHkAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmphkadr(String emphkadr) {
        this.emphkadr = emphkadr == null ? null : emphkadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empLinkmanName
     *
     * @return the value of employee.empLinkmanName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmplinkmanname() {
        return emplinkmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empLinkmanName
     *
     * @param emplinkmanname the value for employee.empLinkmanName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmplinkmanname(String emplinkmanname) {
        this.emplinkmanname = emplinkmanname == null ? null : emplinkmanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empLinkmanAdr
     *
     * @return the value of employee.empLinkmanAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmplinkmanadr() {
        return emplinkmanadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empLinkmanAdr
     *
     * @param emplinkmanadr the value for employee.empLinkmanAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmplinkmanadr(String emplinkmanadr) {
        this.emplinkmanadr = emplinkmanadr == null ? null : emplinkmanadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empLinkmanRelation
     *
     * @return the value of employee.empLinkmanRelation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmplinkmanrelation() {
        return emplinkmanrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empLinkmanRelation
     *
     * @param emplinkmanrelation the value for employee.empLinkmanRelation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmplinkmanrelation(String emplinkmanrelation) {
        this.emplinkmanrelation = emplinkmanrelation == null ? null : emplinkmanrelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.empLinkmanTel
     *
     * @return the value of employee.empLinkmanTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getEmplinkmantel() {
        return emplinkmantel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.empLinkmanTel
     *
     * @param emplinkmantel the value for employee.empLinkmanTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmplinkmantel(String emplinkmantel) {
        this.emplinkmantel = emplinkmantel == null ? null : emplinkmantel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.isDelete
     *
     * @return the value of employee.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.isDelete
     *
     * @param isdelete the value for employee.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}