package com.web.entity;

import java.util.Date;

public class Inpatient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.inpatId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer inpatid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer patid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.deptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.enterTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date entertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.bedId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer bedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.state
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.outTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date outtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inpatient.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    private Patient patient;
    
    public Patient getPatient() {
		return patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.inpatId
     *
     * @return the value of inpatient.inpatId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getInpatid() {
        return inpatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.inpatId
     *
     * @param inpatid the value for inpatient.inpatId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setInpatid(Integer inpatid) {
        this.inpatid = inpatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.patId
     *
     * @return the value of inpatient.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPatid() {
        return patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.patId
     *
     * @param patid the value for inpatient.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatid(Integer patid) {
        this.patid = patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.deptId
     *
     * @return the value of inpatient.deptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.deptId
     *
     * @param deptid the value for inpatient.deptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.enterTime
     *
     * @return the value of inpatient.enterTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getEntertime() {
        return entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.enterTime
     *
     * @param entertime the value for inpatient.enterTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEntertime(Date entertime) {
        this.entertime = entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.bedId
     *
     * @return the value of inpatient.bedId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getBedid() {
        return bedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.bedId
     *
     * @param bedid the value for inpatient.bedId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setBedid(Integer bedid) {
        this.bedid = bedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.state
     *
     * @return the value of inpatient.state
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.state
     *
     * @param state the value for inpatient.state
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.outTime
     *
     * @return the value of inpatient.outTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.outTime
     *
     * @param outtime the value for inpatient.outTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setOuttime(Date outtime) {
        this.outtime = outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inpatient.isDelete
     *
     * @return the value of inpatient.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inpatient.isDelete
     *
     * @param isdelete the value for inpatient.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}