package com.web.entity;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menuId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menuName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menuUrl
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String menuurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menuImage
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String menuimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menuLevel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer menulevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menuSort
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer menusort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuId
     *
     * @return the value of menu.menuId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuId
     *
     * @param menuid the value for menu.menuId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuName
     *
     * @return the value of menu.menuName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuName
     *
     * @param menuname the value for menu.menuName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuUrl
     *
     * @return the value of menu.menuUrl
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuUrl
     *
     * @param menuurl the value for menu.menuUrl
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuImage
     *
     * @return the value of menu.menuImage
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getMenuimage() {
        return menuimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuImage
     *
     * @param menuimage the value for menu.menuImage
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMenuimage(String menuimage) {
        this.menuimage = menuimage == null ? null : menuimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuLevel
     *
     * @return the value of menu.menuLevel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMenulevel() {
        return menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuLevel
     *
     * @param menulevel the value for menu.menuLevel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMenulevel(Integer menulevel) {
        this.menulevel = menulevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuSort
     *
     * @return the value of menu.menuSort
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMenusort() {
        return menusort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuSort
     *
     * @param menusort the value for menu.menuSort
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMenusort(Integer menusort) {
        this.menusort = menusort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.isDelete
     *
     * @return the value of menu.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.isDelete
     *
     * @param isdelete the value for menu.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}