package com.web.entity;

import java.util.Date;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer patid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patSex
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patBirthDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date patbirthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patAge
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer patage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patMaritalStatus
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patmaritalstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patVocation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patvocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patBirthPlace
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patbirthplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patNation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patnation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patIDnumber
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patidnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patNationality
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patnationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patWorkUnitAndAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patworkunitandadr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String pattel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patPostalCode
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patpostalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patHkAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String pathkadr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patLinkmanName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patlinkmanname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patLinkmanAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patlinkmanadr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patLinkmanRelation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patlinkmanrelation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patLinkmanTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String patlinkmantel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patId
     *
     * @return the value of patient.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPatid() {
        return patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patId
     *
     * @param patid the value for patient.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatid(Integer patid) {
        this.patid = patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patName
     *
     * @return the value of patient.patName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatname() {
        return patname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patName
     *
     * @param patname the value for patient.patName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatname(String patname) {
        this.patname = patname == null ? null : patname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patSex
     *
     * @return the value of patient.patSex
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatsex() {
        return patsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patSex
     *
     * @param patsex the value for patient.patSex
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatsex(String patsex) {
        this.patsex = patsex == null ? null : patsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patBirthDate
     *
     * @return the value of patient.patBirthDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getPatbirthdate() {
        return patbirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patBirthDate
     *
     * @param patbirthdate the value for patient.patBirthDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatbirthdate(Date patbirthdate) {
        this.patbirthdate = patbirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patAge
     *
     * @return the value of patient.patAge
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPatage() {
        return patage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patAge
     *
     * @param patage the value for patient.patAge
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatage(Integer patage) {
        this.patage = patage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patMaritalStatus
     *
     * @return the value of patient.patMaritalStatus
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatmaritalstatus() {
        return patmaritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patMaritalStatus
     *
     * @param patmaritalstatus the value for patient.patMaritalStatus
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatmaritalstatus(String patmaritalstatus) {
        this.patmaritalstatus = patmaritalstatus == null ? null : patmaritalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patVocation
     *
     * @return the value of patient.patVocation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatvocation() {
        return patvocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patVocation
     *
     * @param patvocation the value for patient.patVocation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatvocation(String patvocation) {
        this.patvocation = patvocation == null ? null : patvocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patBirthPlace
     *
     * @return the value of patient.patBirthPlace
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatbirthplace() {
        return patbirthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patBirthPlace
     *
     * @param patbirthplace the value for patient.patBirthPlace
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatbirthplace(String patbirthplace) {
        this.patbirthplace = patbirthplace == null ? null : patbirthplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patNation
     *
     * @return the value of patient.patNation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatnation() {
        return patnation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patNation
     *
     * @param patnation the value for patient.patNation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatnation(String patnation) {
        this.patnation = patnation == null ? null : patnation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patIDnumber
     *
     * @return the value of patient.patIDnumber
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatidnumber() {
        return patidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patIDnumber
     *
     * @param patidnumber the value for patient.patIDnumber
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatidnumber(String patidnumber) {
        this.patidnumber = patidnumber == null ? null : patidnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patNationality
     *
     * @return the value of patient.patNationality
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatnationality() {
        return patnationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patNationality
     *
     * @param patnationality the value for patient.patNationality
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatnationality(String patnationality) {
        this.patnationality = patnationality == null ? null : patnationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patWorkUnitAndAdr
     *
     * @return the value of patient.patWorkUnitAndAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatworkunitandadr() {
        return patworkunitandadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patWorkUnitAndAdr
     *
     * @param patworkunitandadr the value for patient.patWorkUnitAndAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatworkunitandadr(String patworkunitandadr) {
        this.patworkunitandadr = patworkunitandadr == null ? null : patworkunitandadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patTel
     *
     * @return the value of patient.patTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPattel() {
        return pattel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patTel
     *
     * @param pattel the value for patient.patTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPattel(String pattel) {
        this.pattel = pattel == null ? null : pattel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patPostalCode
     *
     * @return the value of patient.patPostalCode
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatpostalcode() {
        return patpostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patPostalCode
     *
     * @param patpostalcode the value for patient.patPostalCode
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatpostalcode(String patpostalcode) {
        this.patpostalcode = patpostalcode == null ? null : patpostalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patHkAdr
     *
     * @return the value of patient.patHkAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPathkadr() {
        return pathkadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patHkAdr
     *
     * @param pathkadr the value for patient.patHkAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPathkadr(String pathkadr) {
        this.pathkadr = pathkadr == null ? null : pathkadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patLinkmanName
     *
     * @return the value of patient.patLinkmanName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatlinkmanname() {
        return patlinkmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patLinkmanName
     *
     * @param patlinkmanname the value for patient.patLinkmanName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatlinkmanname(String patlinkmanname) {
        this.patlinkmanname = patlinkmanname == null ? null : patlinkmanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patLinkmanAdr
     *
     * @return the value of patient.patLinkmanAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatlinkmanadr() {
        return patlinkmanadr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patLinkmanAdr
     *
     * @param patlinkmanadr the value for patient.patLinkmanAdr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatlinkmanadr(String patlinkmanadr) {
        this.patlinkmanadr = patlinkmanadr == null ? null : patlinkmanadr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patLinkmanRelation
     *
     * @return the value of patient.patLinkmanRelation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatlinkmanrelation() {
        return patlinkmanrelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patLinkmanRelation
     *
     * @param patlinkmanrelation the value for patient.patLinkmanRelation
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatlinkmanrelation(String patlinkmanrelation) {
        this.patlinkmanrelation = patlinkmanrelation == null ? null : patlinkmanrelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patLinkmanTel
     *
     * @return the value of patient.patLinkmanTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPatlinkmantel() {
        return patlinkmantel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patLinkmanTel
     *
     * @param patlinkmantel the value for patient.patLinkmanTel
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatlinkmantel(String patlinkmantel) {
        this.patlinkmantel = patlinkmantel == null ? null : patlinkmantel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.isDelete
     *
     * @return the value of patient.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.isDelete
     *
     * @param isdelete the value for patient.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }
}