package com.web.entity;

public class Professionaltitle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionaltitle.profId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer profid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionaltitle.profName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String profname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionaltitle.deptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionaltitle.profBaseSalary
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Long profbasesalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professionaltitle.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionaltitle.profId
     *
     * @return the value of professionaltitle.profId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getProfid() {
        return profid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionaltitle.profId
     *
     * @param profid the value for professionaltitle.profId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setProfid(Integer profid) {
        this.profid = profid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionaltitle.profName
     *
     * @return the value of professionaltitle.profName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getProfname() {
        return profname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionaltitle.profName
     *
     * @param profname the value for professionaltitle.profName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setProfname(String profname) {
        this.profname = profname == null ? null : profname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionaltitle.deptId
     *
     * @return the value of professionaltitle.deptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionaltitle.deptId
     *
     * @param deptid the value for professionaltitle.deptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionaltitle.profBaseSalary
     *
     * @return the value of professionaltitle.profBaseSalary
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Long getProfbasesalary() {
        return profbasesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionaltitle.profBaseSalary
     *
     * @param profbasesalary the value for professionaltitle.profBaseSalary
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setProfbasesalary(Long profbasesalary) {
        this.profbasesalary = profbasesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professionaltitle.isDelete
     *
     * @return the value of professionaltitle.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professionaltitle.isDelete
     *
     * @param isdelete the value for professionaltitle.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}