package com.web.entity;

public class TPositionMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_menu.pmId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer pmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_menu.menuId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_position_menu.poId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer poid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_menu.pmId
     *
     * @return the value of t_position_menu.pmId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPmid() {
        return pmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_menu.pmId
     *
     * @param pmid the value for t_position_menu.pmId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPmid(Integer pmid) {
        this.pmid = pmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_menu.menuId
     *
     * @return the value of t_position_menu.menuId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_menu.menuId
     *
     * @param menuid the value for t_position_menu.menuId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position_menu.poId
     *
     * @return the value of t_position_menu.poId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPoid() {
        return poid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position_menu.poId
     *
     * @param poid the value for t_position_menu.poId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPoid(Integer poid) {
        this.poid = poid;
    }
}