package com.web.entity;

import java.util.Date;

public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.attenId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer attenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.workTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date worktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.isAttendant
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isattendant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;
    
    private Employee emp;
    
    public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	public Workinghours getWh() {
		return wh;
	}

	public void setWh(Workinghours wh) {
		this.wh = wh;
	}

	private Workinghours wh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.attenId
     *
     * @return the value of attendance.attenId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getAttenid() {
        return attenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.attenId
     *
     * @param attenid the value for attendance.attenId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setAttenid(Integer attenid) {
        this.attenid = attenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.workTime
     *
     * @return the value of attendance.workTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getWorktime() {
        return worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.workTime
     *
     * @param worktime the value for attendance.workTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setWorktime(Date worktime) {
        this.worktime = worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.isAttendant
     *
     * @return the value of attendance.isAttendant
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsattendant() {
        return isattendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.isAttendant
     *
     * @param isattendant the value for attendance.isAttendant
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsattendant(Integer isattendant) {
        this.isattendant = isattendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.isDelete
     *
     * @return the value of attendance.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.isDelete
     *
     * @param isdelete the value for attendance.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}