package com.web.entity;

import java.util.Date;

public class Doctoradvice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctoradvice.docaId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer docaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctoradvice.docaDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date docadate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctoradvice.docaIllnessExplain
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String docaillnessexplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctoradvice.docaTreatmentScheme
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String docatreatmentscheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctoradvice.docaEmpDocId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer docaempdocid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctoradvice.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer patid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctoradvice.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    private Employee employee;
    private Patient patient;
    
    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctoradvice.docaId
     *
     * @return the value of doctoradvice.docaId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getDocaid() {
        return docaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctoradvice.docaId
     *
     * @param docaid the value for doctoradvice.docaId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDocaid(Integer docaid) {
        this.docaid = docaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctoradvice.docaDate
     *
     * @return the value of doctoradvice.docaDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getDocadate() {
        return docadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctoradvice.docaDate
     *
     * @param docadate the value for doctoradvice.docaDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDocadate(Date docadate) {
        this.docadate = docadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctoradvice.docaIllnessExplain
     *
     * @return the value of doctoradvice.docaIllnessExplain
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getDocaillnessexplain() {
        return docaillnessexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctoradvice.docaIllnessExplain
     *
     * @param docaillnessexplain the value for doctoradvice.docaIllnessExplain
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDocaillnessexplain(String docaillnessexplain) {
        this.docaillnessexplain = docaillnessexplain == null ? null : docaillnessexplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctoradvice.docaTreatmentScheme
     *
     * @return the value of doctoradvice.docaTreatmentScheme
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getDocatreatmentscheme() {
        return docatreatmentscheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctoradvice.docaTreatmentScheme
     *
     * @param docatreatmentscheme the value for doctoradvice.docaTreatmentScheme
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDocatreatmentscheme(String docatreatmentscheme) {
        this.docatreatmentscheme = docatreatmentscheme == null ? null : docatreatmentscheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctoradvice.docaEmpDocId
     *
     * @return the value of doctoradvice.docaEmpDocId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getDocaempdocid() {
        return docaempdocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctoradvice.docaEmpDocId
     *
     * @param docaempdocid the value for doctoradvice.docaEmpDocId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDocaempdocid(Integer docaempdocid) {
        this.docaempdocid = docaempdocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctoradvice.patId
     *
     * @return the value of doctoradvice.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPatid() {
        return patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctoradvice.patId
     *
     * @param patid the value for doctoradvice.patId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPatid(Integer patid) {
        this.patid = patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctoradvice.isDelete
     *
     * @return the value of doctoradvice.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctoradvice.isDelete
     *
     * @param isdelete the value for doctoradvice.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}