package com.web.entity;

import java.util.Date;

public class Dutytable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dutytable.dutyDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
	private int dutyid;
	
    

	public int getDutyid() {
		return dutyid;
	}

	public void setDutyid(int dutyid) {
		this.dutyid = dutyid;
	}

	private Date dutydate;
	
	private Employee emp;
	

    public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dutytable.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer empid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dutytable.wardName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String wardname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dutytable.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dutytable.dutyDate
     *
     * @return the value of dutytable.dutyDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getDutydate() {
        return dutydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dutytable.dutyDate
     *
     * @param dutydate the value for dutytable.dutyDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDutydate(Date dutydate) {
        this.dutydate = dutydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dutytable.empId
     *
     * @return the value of dutytable.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dutytable.empId
     *
     * @param empid the value for dutytable.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dutytable.wardName
     *
     * @return the value of dutytable.wardName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getWardname() {
        return wardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dutytable.wardName
     *
     * @param wardname the value for dutytable.wardName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setWardname(String wardname) {
        this.wardname = wardname == null ? null : wardname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dutytable.isDelete
     *
     * @return the value of dutytable.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dutytable.isDelete
     *
     * @param isdelete the value for dutytable.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}