package com.web.entity;

public class Facilities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.faciId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer faciid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.faciName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String faciname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.faciPrice
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float faciprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.faciNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer facinum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.faciFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String facifirm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.faciDeptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer facideptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilities.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;
    
    private Department dep;

    public Department getDep() {
		return dep;
	}

	public void setDep(Department dep) {
		this.dep = dep;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.faciId
     *
     * @return the value of facilities.faciId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getFaciid() {
        return faciid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.faciId
     *
     * @param faciid the value for facilities.faciId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFaciid(Integer faciid) {
        this.faciid = faciid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.faciName
     *
     * @return the value of facilities.faciName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getFaciname() {
        return faciname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.faciName
     *
     * @param faciname the value for facilities.faciName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFaciname(String faciname) {
        this.faciname = faciname == null ? null : faciname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.faciPrice
     *
     * @return the value of facilities.faciPrice
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getFaciprice() {
        return faciprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.faciPrice
     *
     * @param faciprice the value for facilities.faciPrice
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFaciprice(Float faciprice) {
        this.faciprice = faciprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.faciNum
     *
     * @return the value of facilities.faciNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getFacinum() {
        return facinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.faciNum
     *
     * @param facinum the value for facilities.faciNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFacinum(Integer facinum) {
        this.facinum = facinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.faciFirm
     *
     * @return the value of facilities.faciFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getFacifirm() {
        return facifirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.faciFirm
     *
     * @param facifirm the value for facilities.faciFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFacifirm(String facifirm) {
        this.facifirm = facifirm == null ? null : facifirm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.faciDeptId
     *
     * @return the value of facilities.faciDeptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getFacideptid() {
        return facideptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.faciDeptId
     *
     * @param facideptid the value for facilities.faciDeptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFacideptid(Integer facideptid) {
        this.facideptid = facideptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilities.isDelete
     *
     * @return the value of facilities.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilities.isDelete
     *
     * @param isdelete the value for facilities.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}