package com.web.entity;

import java.util.Date;

public class Facilityrepair {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilityrepair.faciId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer faciid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilityrepair.facireDeptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer faciredeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilityrepair.facireBudget
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float facirebudget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilityrepair.facireDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date faciredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilityrepair.facireFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String facirefirm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilityrepair.facireFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float facirefee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column facilityrepair.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;
    
    private Department dept;
    
    public Department getDept() {
		return dept;
	}

	public void setDept(Department dept) {
		this.dept = dept;
	}

	public Facilities getFc() {
		return fc;
	}

	public void setFc(Facilities fc) {
		this.fc = fc;
	}

	private Facilities fc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilityrepair.faciId
     *
     * @return the value of facilityrepair.faciId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getFaciid() {
        return faciid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilityrepair.faciId
     *
     * @param faciid the value for facilityrepair.faciId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFaciid(Integer faciid) {
        this.faciid = faciid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilityrepair.facireDeptId
     *
     * @return the value of facilityrepair.facireDeptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getFaciredeptid() {
        return faciredeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilityrepair.facireDeptId
     *
     * @param faciredeptid the value for facilityrepair.facireDeptId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFaciredeptid(Integer faciredeptid) {
        this.faciredeptid = faciredeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilityrepair.facireBudget
     *
     * @return the value of facilityrepair.facireBudget
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getFacirebudget() {
        return facirebudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilityrepair.facireBudget
     *
     * @param facirebudget the value for facilityrepair.facireBudget
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFacirebudget(Float facirebudget) {
        this.facirebudget = facirebudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilityrepair.facireDate
     *
     * @return the value of facilityrepair.facireDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getFaciredate() {
        return faciredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilityrepair.facireDate
     *
     * @param faciredate the value for facilityrepair.facireDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFaciredate(Date faciredate) {
        this.faciredate = faciredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilityrepair.facireFirm
     *
     * @return the value of facilityrepair.facireFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getFacirefirm() {
        return facirefirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilityrepair.facireFirm
     *
     * @param facirefirm the value for facilityrepair.facireFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFacirefirm(String facirefirm) {
        this.facirefirm = facirefirm == null ? null : facirefirm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilityrepair.facireFee
     *
     * @return the value of facilityrepair.facireFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getFacirefee() {
        return facirefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilityrepair.facireFee
     *
     * @param facirefee the value for facilityrepair.facireFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setFacirefee(Float facirefee) {
        this.facirefee = facirefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column facilityrepair.isDelete
     *
     * @return the value of facilityrepair.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column facilityrepair.isDelete
     *
     * @param isdelete the value for facilityrepair.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}