package com.web.entity;

import java.util.Date;

public class Medicinepayreceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinepayreceipt.mprId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer mprid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinepayreceipt.maId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer maid;
	private Medicaladvice med;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinepayreceipt.mprContent
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String mprcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinepayreceipt.inpatId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer inpatid;
	private Inpatient inp;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinepayreceipt.mprDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date mprdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinepayreceipt.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer empid;
	private Employee emp;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinepayreceipt.amount
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float amount;
	private Patient pat;
    private Integer isdelete;
    public Medicaladvice getMed() {
		return med;
	}

	public void setMed(Medicaladvice med) {
		this.med = med;
	}

	public Inpatient getInp() {
		return inp;
	}

	public void setInp(Inpatient inp) {
		this.inp = inp;
	}

	public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	public Patient getPat() {
		return pat;
	}

	public void setPat(Patient pat) {
		this.pat = pat;
	}

	public Integer getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinepayreceipt.mprId
     *
     * @return the value of medicinepayreceipt.mprId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMprid() {
        return mprid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinepayreceipt.mprId
     *
     * @param mprid the value for medicinepayreceipt.mprId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMprid(Integer mprid) {
        this.mprid = mprid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinepayreceipt.maId
     *
     * @return the value of medicinepayreceipt.maId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMaid() {
        return maid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinepayreceipt.maId
     *
     * @param maid the value for medicinepayreceipt.maId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMaid(Integer maid) {
        this.maid = maid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinepayreceipt.mprContent
     *
     * @return the value of medicinepayreceipt.mprContent
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getMprcontent() {
        return mprcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinepayreceipt.mprContent
     *
     * @param mprcontent the value for medicinepayreceipt.mprContent
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMprcontent(String mprcontent) {
        this.mprcontent = mprcontent == null ? null : mprcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinepayreceipt.inpatId
     *
     * @return the value of medicinepayreceipt.inpatId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getInpatid() {
        return inpatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinepayreceipt.inpatId
     *
     * @param inpatid the value for medicinepayreceipt.inpatId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setInpatid(Integer inpatid) {
        this.inpatid = inpatid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinepayreceipt.mprDate
     *
     * @return the value of medicinepayreceipt.mprDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getMprdate() {
        return mprdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinepayreceipt.mprDate
     *
     * @param mprdate the value for medicinepayreceipt.mprDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMprdate(Date mprdate) {
        this.mprdate = mprdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinepayreceipt.empId
     *
     * @return the value of medicinepayreceipt.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinepayreceipt.empId
     *
     * @param empid the value for medicinepayreceipt.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinepayreceipt.amount
     *
     * @return the value of medicinepayreceipt.amount
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinepayreceipt.amount
     *
     * @param amount the value for medicinepayreceipt.amount
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }
}