package com.web.entity;

public class Medicinelibrary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinelibrary.meLiId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer meliid;
    
    private Employee emp;
    
    

    public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinelibrary.meLiMan
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer meliman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinelibrary.meLiAddr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String meliaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinelibrary.meLiArea
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float meliarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinelibrary.meLiUnit
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String meliunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicinelibrary.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinelibrary.meLiId
     *
     * @return the value of medicinelibrary.meLiId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMeliid() {
        return meliid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinelibrary.meLiId
     *
     * @param meliid the value for medicinelibrary.meLiId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMeliid(Integer meliid) {
        this.meliid = meliid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinelibrary.meLiMan
     *
     * @return the value of medicinelibrary.meLiMan
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMeliman() {
        return meliman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinelibrary.meLiMan
     *
     * @param meliman the value for medicinelibrary.meLiMan
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMeliman(Integer meliman) {
        this.meliman = meliman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinelibrary.meLiAddr
     *
     * @return the value of medicinelibrary.meLiAddr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getMeliaddr() {
        return meliaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinelibrary.meLiAddr
     *
     * @param meliaddr the value for medicinelibrary.meLiAddr
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMeliaddr(String meliaddr) {
        this.meliaddr = meliaddr == null ? null : meliaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinelibrary.meLiArea
     *
     * @return the value of medicinelibrary.meLiArea
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getMeliarea() {
        return meliarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinelibrary.meLiArea
     *
     * @param meliarea the value for medicinelibrary.meLiArea
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMeliarea(Float meliarea) {
        this.meliarea = meliarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinelibrary.meLiUnit
     *
     * @return the value of medicinelibrary.meLiUnit
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getMeliunit() {
        return meliunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinelibrary.meLiUnit
     *
     * @param meliunit the value for medicinelibrary.meLiUnit
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMeliunit(String meliunit) {
        this.meliunit = meliunit == null ? null : meliunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicinelibrary.isDelete
     *
     * @return the value of medicinelibrary.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicinelibrary.isDelete
     *
     * @param isdelete the value for medicinelibrary.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}