package com.web.entity;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.supId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer supid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer ordnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordOrdDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date ordorddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordDelDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date orddeldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer empid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;
    
    
    private Supplier sup;
    
    private Employee emp;
    
    public Supplier getSup() {
		return sup;
	}

	public void setSup(Supplier sup) {
		this.sup = sup;
	}

	public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordId
     *
     * @return the value of order.ordId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordId
     *
     * @param ordid the value for order.ordId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setOrdid(Integer ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.supId
     *
     * @return the value of order.supId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getSupid() {
        return supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.supId
     *
     * @param supid the value for order.supId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSupid(Integer supid) {
        this.supid = supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordNum
     *
     * @return the value of order.ordNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getOrdnum() {
        return ordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordNum
     *
     * @param ordnum the value for order.ordNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setOrdnum(Integer ordnum) {
        this.ordnum = ordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordOrdDate
     *
     * @return the value of order.ordOrdDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getOrdorddate() {
        return ordorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordOrdDate
     *
     * @param ordorddate the value for order.ordOrdDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setOrdorddate(Date ordorddate) {
        this.ordorddate = ordorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordDelDate
     *
     * @return the value of order.ordDelDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getOrddeldate() {
        return orddeldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordDelDate
     *
     * @param orddeldate the value for order.ordDelDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setOrddeldate(Date orddeldate) {
        this.orddeldate = orddeldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.empId
     *
     * @return the value of order.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.empId
     *
     * @param empid the value for order.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.isDelete
     *
     * @return the value of order.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.isDelete
     *
     * @param isdelete the value for order.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}