package com.web.entity;

public class Orderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.DetId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer detid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.ordId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.mediId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer mediid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.DetNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer detnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.DetTotalFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float dettotalfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.DetBatchNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String detbatchnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Order orders;
    

	public Order getOrders() {
		return orders;
	}

	public void setOrders(Order orders) {
		this.orders = orders;
	}

	public Medicine getMedicine() {
		return medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	private Medicine medicine;
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.DetId
     *
     * @return the value of orderdetail.DetId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getDetid() {
        return detid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.DetId
     *
     * @param detid the value for orderdetail.DetId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDetid(Integer detid) {
        this.detid = detid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.ordId
     *
     * @return the value of orderdetail.ordId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.ordId
     *
     * @param ordid the value for orderdetail.ordId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setOrdid(Integer ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.mediId
     *
     * @return the value of orderdetail.mediId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMediid() {
        return mediid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.mediId
     *
     * @param mediid the value for orderdetail.mediId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMediid(Integer mediid) {
        this.mediid = mediid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.DetNum
     *
     * @return the value of orderdetail.DetNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getDetnum() {
        return detnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.DetNum
     *
     * @param detnum the value for orderdetail.DetNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDetnum(Integer detnum) {
        this.detnum = detnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.DetTotalFee
     *
     * @return the value of orderdetail.DetTotalFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getDettotalfee() {
        return dettotalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.DetTotalFee
     *
     * @param dettotalfee the value for orderdetail.DetTotalFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDettotalfee(Float dettotalfee) {
        this.dettotalfee = dettotalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.DetBatchNum
     *
     * @return the value of orderdetail.DetBatchNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getDetbatchnum() {
        return detbatchnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.DetBatchNum
     *
     * @param detbatchnum the value for orderdetail.DetBatchNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setDetbatchnum(String detbatchnum) {
        this.detbatchnum = detbatchnum == null ? null : detbatchnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.isDelete
     *
     * @return the value of orderdetail.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.isDelete
     *
     * @param isdelete the value for orderdetail.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}