package com.web.entity;

public class Prescription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.presId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer presid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.mediId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer mediid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.mediNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer medinum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.presDocaId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer presdocaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    //外键
    private Doctoradvice doctoradvice;
    
    private Medicine medicine;
    
    public Medicine getMedicine() {
        return medicine;
    }

    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }

    public Doctoradvice getDoctoradvice() {
        return doctoradvice;
    }

    public void setDoctoradvice(Doctoradvice doctoradvice) {
        this.doctoradvice = doctoradvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.presId
     *
     * @return the value of prescription.presId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPresid() {
        return presid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.presId
     *
     * @param presid the value for prescription.presId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPresid(Integer presid) {
        this.presid = presid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.mediId
     *
     * @return the value of prescription.mediId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMediid() {
        return mediid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.mediId
     *
     * @param mediid the value for prescription.mediId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMediid(Integer mediid) {
        this.mediid = mediid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.mediNum
     *
     * @return the value of prescription.mediNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getMedinum() {
        return medinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.mediNum
     *
     * @param medinum the value for prescription.mediNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setMedinum(Integer medinum) {
        this.medinum = medinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.presDocaId
     *
     * @return the value of prescription.presDocaId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPresdocaid() {
        return presdocaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.presDocaId
     *
     * @param presdocaid the value for prescription.presDocaId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPresdocaid(Integer presdocaid) {
        this.presdocaid = presdocaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.isDelete
     *
     * @return the value of prescription.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.isDelete
     *
     * @param isdelete the value for prescription.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}