package com.web.entity;

import java.util.Date;

public class Purchase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer purid;
    private Integer isdelete;
    
    private Integer supid;
    private Integer empid;
    private Employee emp;
    private Supplier sup;

	public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	public Supplier getSup() {
		return sup;
	}

	public void setSup(Supplier sup) {
		this.sup = sup;
	}

	public Integer getSupid() {
		return supid;
	}

	public void setSupid(Integer supid) {
		this.supid = supid;
	}

	public Integer getEmpid() {
		return empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	public Integer getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String purname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    //private String purfirm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purMan
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
   // private String purman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date purdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer purnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float purfee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purId
     *
     * @return the value of purchase.purId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPurid() {
        return purid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purId
     *
     * @param purid the value for purchase.purId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPurid(Integer purid) {
        this.purid = purid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purName
     *
     * @return the value of purchase.purName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getPurname() {
        return purname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purName
     *
     * @param purname the value for purchase.purName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPurname(String purname) {
        this.purname = purname == null ? null : purname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purFirm
     *
     * @return the value of purchase.purFirm
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purDate
     *
     * @return the value of purchase.purDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getPurdate() {
        return purdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purDate
     *
     * @param purdate the value for purchase.purDate
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPurdate(Date purdate) {
        this.purdate = purdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purNum
     *
     * @return the value of purchase.purNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getPurnum() {
        return purnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purNum
     *
     * @param purnum the value for purchase.purNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPurnum(Integer purnum) {
        this.purnum = purnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purFee
     *
     * @return the value of purchase.purFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getPurfee() {
        return purfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purFee
     *
     * @param purfee the value for purchase.purFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setPurfee(Float purfee) {
        this.purfee = purfee;
    }
}