package com.web.entity;

public class Supplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supId
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private Integer supid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supName
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private String supname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supAddr
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private String supaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supTel
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private String suptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supCreditConditions
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private String supcreditconditions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.isDelete
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supId
     *
     * @return the value of supplier.supId
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public Integer getSupid() {
        return supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supId
     *
     * @param supid the value for supplier.supId
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setSupid(Integer supid) {
        this.supid = supid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supName
     *
     * @return the value of supplier.supName
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public String getSupname() {
        return supname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supName
     *
     * @param supname the value for supplier.supName
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setSupname(String supname) {
        this.supname = supname == null ? null : supname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supAddr
     *
     * @return the value of supplier.supAddr
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public String getSupaddr() {
        return supaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supAddr
     *
     * @param supaddr the value for supplier.supAddr
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setSupaddr(String supaddr) {
        this.supaddr = supaddr == null ? null : supaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supTel
     *
     * @return the value of supplier.supTel
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public String getSuptel() {
        return suptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supTel
     *
     * @param suptel the value for supplier.supTel
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setSuptel(String suptel) {
        this.suptel = suptel == null ? null : suptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supCreditConditions
     *
     * @return the value of supplier.supCreditConditions
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public String getSupcreditconditions() {
        return supcreditconditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supCreditConditions
     *
     * @param supcreditconditions the value for supplier.supCreditConditions
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setSupcreditconditions(String supcreditconditions) {
        this.supcreditconditions = supcreditconditions == null ? null : supcreditconditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.isDelete
     *
     * @return the value of supplier.isDelete
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.isDelete
     *
     * @param isdelete the value for supplier.isDelete
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}