package com.web.entity;

public class Surgery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgery.surgId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer surgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgery.surgName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String surgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgery.surgProfId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer surgprofid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgery.surgPushFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float surgpushfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgery.surgFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float surgfee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgery.surgId
     *
     * @return the value of surgery.surgId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Professionaltitle professionaltitle;
    
    public Professionaltitle getProfessionaltitle() {
		return professionaltitle;
	}

	public void setProfessionaltitle(Professionaltitle professionaltitle) {
		this.professionaltitle = professionaltitle;
	}

	private Integer isdelete;
    public Integer getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	public Integer getSurgid() {
        return surgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgery.surgId
     *
     * @param surgid the value for surgery.surgId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurgid(Integer surgid) {
        this.surgid = surgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgery.surgName
     *
     * @return the value of surgery.surgName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getSurgname() {
        return surgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgery.surgName
     *
     * @param surgname the value for surgery.surgName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurgname(String surgname) {
        this.surgname = surgname == null ? null : surgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgery.surgProfId
     *
     * @return the value of surgery.surgProfId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getSurgprofid() {
        return surgprofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgery.surgProfId
     *
     * @param surgprofid the value for surgery.surgProfId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurgprofid(Integer surgprofid) {
        this.surgprofid = surgprofid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgery.surgPushFee
     *
     * @return the value of surgery.surgPushFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getSurgpushfee() {
        return surgpushfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgery.surgPushFee
     *
     * @param surgpushfee the value for surgery.surgPushFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurgpushfee(Float surgpushfee) {
        this.surgpushfee = surgpushfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgery.surgFee
     *
     * @return the value of surgery.surgFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getSurgfee() {
        return surgfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgery.surgFee
     *
     * @param surgfee the value for surgery.surgFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurgfee(Float surgfee) {
        this.surgfee = surgfee;
    }
}