package com.web.entity;

public class Surgerycommission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgerycommission.surcId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer surcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgerycommission.surcType
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String surctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surgerycommission.surcPushFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float surcpushfee;
    
    private Integer isdelete;
    
    private Employee emp;
    

    public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	

	public Integer getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgerycommission.surcId
     *
     * @return the value of surgerycommission.surcId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getSurcid() {
        return surcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgerycommission.surcId
     *
     * @param surcid the value for surgerycommission.surcId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurcid(Integer surcid) {
        this.surcid = surcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgerycommission.surcType
     *
     * @return the value of surgerycommission.surcType
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getSurctype() {
        return surctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgerycommission.surcType
     *
     * @param surctype the value for surgerycommission.surcType
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurctype(String surctype) {
        this.surctype = surctype == null ? null : surctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surgerycommission.surcPushFee
     *
     * @return the value of surgerycommission.surcPushFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getSurcpushfee() {
        return surcpushfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surgerycommission.surcPushFee
     *
     * @param surcpushfee the value for surgerycommission.surcPushFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setSurcpushfee(Float surcpushfee) {
        this.surcpushfee = surcpushfee;
    }
}