package com.web.entity;

public class Testitems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitems.testId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer testid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitems.testName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String testname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitems.testType
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String testtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitems.testFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Float testfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitems.testExplain
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String testexplain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitems.testTaboo
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String testtaboo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testitems.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitems.testId
     *
     * @return the value of testitems.testId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitems.testId
     *
     * @param testid the value for testitems.testId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTestid(Integer testid) {
        this.testid = testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitems.testName
     *
     * @return the value of testitems.testName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getTestname() {
        return testname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitems.testName
     *
     * @param testname the value for testitems.testName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTestname(String testname) {
        this.testname = testname == null ? null : testname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitems.testType
     *
     * @return the value of testitems.testType
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getTesttype() {
        return testtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitems.testType
     *
     * @param testtype the value for testitems.testType
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTesttype(String testtype) {
        this.testtype = testtype == null ? null : testtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitems.testFee
     *
     * @return the value of testitems.testFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Float getTestfee() {
        return testfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitems.testFee
     *
     * @param testfee the value for testitems.testFee
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTestfee(Float testfee) {
        this.testfee = testfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitems.testExplain
     *
     * @return the value of testitems.testExplain
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getTestexplain() {
        return testexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitems.testExplain
     *
     * @param testexplain the value for testitems.testExplain
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTestexplain(String testexplain) {
        this.testexplain = testexplain == null ? null : testexplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitems.testTaboo
     *
     * @return the value of testitems.testTaboo
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getTesttaboo() {
        return testtaboo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitems.testTaboo
     *
     * @param testtaboo the value for testitems.testTaboo
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTesttaboo(String testtaboo) {
        this.testtaboo = testtaboo == null ? null : testtaboo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testitems.isDelete
     *
     * @return the value of testitems.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testitems.isDelete
     *
     * @param isdelete the value for testitems.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}