package com.web.entity;

public class Travelarrange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelarrange.travelId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer travelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelarrange.travelEmpId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer travelempid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelarrange.travelLicence
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String travellicence;
    
    
    private int isdelete;
    
	private Employee emp;
    
    public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	private Travelactivities travelactivities;
    
    
    public Travelactivities getTravelactivities() {
		return travelactivities;
	}

	public void setTravelactivities(Travelactivities travelactivities) {
		this.travelactivities = travelactivities;
	}

	public int getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(int isdelete) {
		this.isdelete = isdelete;
	}






    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelarrange.travelId
     *
     * @return the value of travelarrange.travelId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getTravelid() {
        return travelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelarrange.travelId
     *
     * @param travelid the value for travelarrange.travelId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTravelid(Integer travelid) {
        this.travelid = travelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelarrange.travelEmpId
     *
     * @return the value of travelarrange.travelEmpId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getTravelempid() {
        return travelempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelarrange.travelEmpId
     *
     * @param travelempid the value for travelarrange.travelEmpId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTravelempid(Integer travelempid) {
        this.travelempid = travelempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelarrange.travelLicence
     *
     * @return the value of travelarrange.travelLicence
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getTravellicence() {
        return travellicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelarrange.travelLicence
     *
     * @param travellicence the value for travelarrange.travelLicence
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setTravellicence(String travellicence) {
        this.travellicence = travellicence == null ? null : travellicence.trim();
    }
}