package com.web.entity;

import java.util.Date;

public class Travelactivities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelactivities.traId
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
	private String traname;
    public String getTraname() {
		return traname;
	}

	public void setTraname(String traname) {
		this.traname = traname;
	}

	private Integer traid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelactivities.traDest
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private String tradest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelactivities.traStart
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private String trastart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelactivities.traContent
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private String tracontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelactivities.traFee
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private Float trafee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelactivities.traDate
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    private Date tradate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelactivities.traId
     *
     * @return the value of travelactivities.traId
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    
    private Integer isdelete;
    
    public Integer getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	public Integer getTraid() {
        return traid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelactivities.traId
     *
     * @param traid the value for travelactivities.traId
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setTraid(Integer traid) {
        this.traid = traid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelactivities.traDest
     *
     * @return the value of travelactivities.traDest
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public String getTradest() {
        return tradest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelactivities.traDest
     *
     * @param tradest the value for travelactivities.traDest
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setTradest(String tradest) {
        this.tradest = tradest == null ? null : tradest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelactivities.traStart
     *
     * @return the value of travelactivities.traStart
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public String getTrastart() {
        return trastart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelactivities.traStart
     *
     * @param trastart the value for travelactivities.traStart
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setTrastart(String trastart) {
        this.trastart = trastart == null ? null : trastart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelactivities.traContent
     *
     * @return the value of travelactivities.traContent
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public String getTracontent() {
        return tracontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelactivities.traContent
     *
     * @param tracontent the value for travelactivities.traContent
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setTracontent(String tracontent) {
        this.tracontent = tracontent == null ? null : tracontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelactivities.traFee
     *
     * @return the value of travelactivities.traFee
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public Float getTrafee() {
        return trafee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelactivities.traFee
     *
     * @param trafee the value for travelactivities.traFee
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setTrafee(Float trafee) {
        this.trafee = trafee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelactivities.traDate
     *
     * @return the value of travelactivities.traDate
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public Date getTradate() {
        return tradate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelactivities.traDate
     *
     * @param tradate the value for travelactivities.traDate
     *
     * @mbg.generated Fri Jun 28 15:08:04 CST 2019
     */
    public void setTradate(Date tradate) {
        this.tradate = tradate;
    }
}