package com.web.entity;

public class Ward {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward.wardName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private String wardname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward.bedNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer bednum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer empid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward.emptyBedNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer emptybednum;
	private Employee emp;
    public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ward.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward.wardName
     *
     * @return the value of ward.wardName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public String getWardname() {
        return wardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward.wardName
     *
     * @param wardname the value for ward.wardName
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setWardname(String wardname) {
        this.wardname = wardname == null ? null : wardname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward.bedNum
     *
     * @return the value of ward.bedNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getBednum() {
        return bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward.bedNum
     *
     * @param bednum the value for ward.bedNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setBednum(Integer bednum) {
        this.bednum = bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward.empId
     *
     * @return the value of ward.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward.empId
     *
     * @param empid the value for ward.empId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward.emptyBedNum
     *
     * @return the value of ward.emptyBedNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getEmptybednum() {
        return emptybednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward.emptyBedNum
     *
     * @param emptybednum the value for ward.emptyBedNum
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setEmptybednum(Integer emptybednum) {
        this.emptybednum = emptybednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ward.isDelete
     *
     * @return the value of ward.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ward.isDelete
     *
     * @param isdelete the value for ward.isDelete
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}