package com.web.entity;

import java.util.Date;

public class Workinghours {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workinghours.workTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Date worktime;

    
    private Integer workid;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workinghours.workEmpId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    private Integer workempid;

    private Employee employee;
    
    public Employee getEmployee() {
        return employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Integer getWorkid() {
		return workid;
	}

	public void setWorkid(Integer workid) {
		this.workid = workid;
	}

	private Integer isdelete;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workinghours.workTime
     *
     * @return the value of workinghours.workTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Date getWorktime() {
        return worktime;
    }

    public Integer getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workinghours.workTime
     *
     * @param worktime the value for workinghours.workTime
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setWorktime(Date worktime) {
        this.worktime = worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workinghours.workEmpId
     *
     * @return the value of workinghours.workEmpId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public Integer getWorkempid() {
        return workempid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workinghours.workEmpId
     *
     * @param workempid the value for workinghours.workEmpId
     *
     * @mbg.generated Mon Jul 01 11:34:33 CST 2019
     */
    public void setWorkempid(Integer workempid) {
        this.workempid = workempid;
    }
}